# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [2]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
pd.options.mode.chained_assignment = None  # default='warn'
import numpy as np
import requests
import gmaps
import os


# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [3]:
# Create city dataframe
city500_weather_data_df = pd.read_csv('../output_data/city500_weather_data.csv')
city500_weather_data_df.dropna(inplace = True) 
city500_weather_data_df.head()

,city_name,country_code,lattitude,longitude,temp,wind_speed,cloudiness,humidity
0,busselton,au,-43.622197,85.473470,62.38,6.46,0,87
1,husavik,is,65.305993,-16.662665,28.40,27.63,90,93
2,ponta do sol,cv,18.716883,-28.049900,77.00,24.16,98,57
3,terrace bay,ca,47.759735,-87.885475,1.40,2.30,90,71
4,flinders,au,-35.240961,131.271820,73.45,8.05,90,88

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [4]:
gmaps.configure(api_key=g_key)

# Store latitude and longitude in locations
locations = city500_weather_data_df[["lattitude", "longitude"]]

# Fill NaN values and convert to float
rating = city500_weather_data_df["humidity"].astype(float)

In [6]:
# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=rating, 
                                 dissipating=False, max_intensity=10,
                                 point_radius=1)


# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [7]:
ideal_city_df= city500_weather_data_df.query('temp < 80 and temp > 70 and wind_speed < 20 and cloudiness < 10')
ideal_city_df

,city_name,country_code,lattitude,longitude,temp,wind_speed,cloudiness,humidity
15,hermanus,za,-76.858641,3.633618,75.00,11.01,1,62
18,cape town,za,-56.949831,-5.953827,79.03,9.22,0,41
19,butaritari,ki,15.350799,159.225820,78.94,10.29,0,84
34,umm lajj,sa,23.622948,38.836667,77.40,8.43,1,41
38,singarayakonda,in,15.205904,80.446437,76.42,10.25,3,71
74,palasa,in,14.981839,87.747987,72.12,2.84,8,85
85,panaba,mx,24.359082,-87.997108,70.77,6.31,2,89
106,cidreira,br,-54.642570,-21.672476,78.42,7.81,1,71
111,adrar,dz,25.177715,3.926631,78.82,10.96,0,16
130,atuona,pf,-8.954727,-120.217511,77.67,16.15,5,80
180,champerico,gt,9.327559,-95.047735,75.20,1.48,0,73
181,abu dhabi,ae,24.404274,53.246499,70.57,11.50,0,64
221,bubaque,gw,6.143722,-19.411378,77.74,6.60,8,45
223,roma,au,-27.345115,144.572667,74.07,16.89,0,56
283,pisco,pe,-18.786417,-86.184735,73.22,9.22,0,78
298,malatap,ph,14.148330,122.515449,74.17,1.81,0,94
310,agadez,ne,16.743115,9.306500,73.09,8.37,0,17
312,batticaloa,lk,9.073142,85.431076,77.52,10.18,3,77
320,waddan,ly,29.624469,16.284281,70.02,10.76,0,21
366,port blair,in,9.682972,88.769471,77.85,8.61,0,66
404,emerald,au,-23.431756,145.288340,73.80,9.22,0,73
409,cozumel,mx,19.162059,-86.047380,79.43,6.91,1,78
416,rawson,ar,-44.497422,-64.149277,70.20,18.84,0,58
418,kanniyakumari,in,6.938740,77.194825,79.14,14.81,5,76
429,dubai,ae,24.578238,55.777275,70.07,13.80,0,46
437,freire,cl,-38.839222,-72.705689,78.80,10.36,0,61
489,trincomalee,lk,10.865806,85.379211,78.49,10.67,1,74

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [17]:
ideal_city_df['hotel_name'] = ""
ideal_city_df['hotel_address'] = ""
ideal_city_df.head()

,city_name,country_code,lattitude,longitude,temp,wind_speed,cloudiness,humidity,hotel_name,hotel_address
15,hermanus,za,-76.858641,3.633618,75.00,11.01,1,62,,
18,cape town,za,-56.949831,-5.953827,79.03,9.22,0,41,,
19,butaritari,ki,15.350799,159.225820,78.94,10.29,0,84,,
34,umm lajj,sa,23.622948,38.836667,77.40,8.43,1,41,,
38,singarayakonda,in,15.205904,80.446437,76.42,10.25,3,71,,

In [47]:

#locations = ideal_city_df[["lattitude", "longitude"]]
# find the closest restaurant of each type to coordinates
for index, row in ideal_city_df.iterrows():
    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    location= str(row['lattitude']) + ',' + str(row['longitude'])
    print(location)
    params = {
        "location": location, # city coorinates
        "rankby": "distance",
        "type": "lodging",
        "radius" : '8000',
        "key": g_key,
        }
    response = requests.get(base_url, params=params).json()
    results = response['results']

    
    try:
        print(f"Closest {row['city_name']} hotel is {results[0]['name']}.")
        
        ideal_city_df.loc[index, 'hotel_name'] = results[0]['name']
        ideal_city_df.loc[index, 'hotel_address'] = results[0]['vicinity']
        
        
    except (KeyError, IndexError):
        print(f"Missing field/result... skipping. ")

-76.85864137373008,3.633617751627355
Missing field/result... skipping.
-56.94983140268718,-5.953826891493152
Missing field/result... skipping.
15.350799292730102,159.22582016392946
Missing field/result... skipping.
23.622948462632408,38.83666729329357
Missing field/result... skipping.
15.205904246409759,80.44643711234295
Missing field/result... skipping.
14.98183912062953,87.74798743720658
Missing field/result... skipping.
24.35908166274696,-87.99710779892266
Missing field/result... skipping.
-54.64256956979804,-21.672475513051577
Missing field/result... skipping.
25.177714578507267,3.9266307929185866
Missing field/result... skipping.
-8.954726707428906,-120.21751085349115
Missing field/result... skipping.
9.327558909784374,-95.04773461770093
Missing field/result... skipping.
24.40427432786777,53.246499065037774
Missing field/result... skipping.
6.143722229379435,-19.411377880939764
Missing field/result... skipping.
-27.34511529667593,144.5726673554503
Missing field/result... skipping.
-18.786417074486522,-86.18473548465248
Missing field/result... skipping.
14.148329778474743,122.51544855131728
Missing field/result... skipping.
16.743115052907978,9.306499847542568
Missing field/result... skipping.
9.073142305739225,85.43107559803786
Missing field/result... skipping.
29.62446851271247,16.28428123149351
Missing field/result... skipping.
9.682972215588848,88.76947098855827
Missing field/result... skipping.
-23.43175567502527,145.2883395155796
Missing field/result... skipping.
19.162059363245817,-86.04737960138897
Missing field/result... skipping.
-44.49742212861897,-64.14927721771781
Missing field/result... skipping.
6.93874000274046,77.19482482700391
Missing field/result... skipping.
24.57823751117529,55.777275208602674
Missing field/result... skipping.
-38.83922246618268,-72.70568908982497
Missing field/result... skipping.
10.865805780878704,85.37921102508096
Missing field/result... skipping.

In [48]:
# Convert hote_name  to a list
# Convert city name  to list
hotel_name = ideal_city_df["hotel_name"].tolist()
city_name= ideal_city_df["city_name"].tolist()
country_name = ideal_city_df["country_code"].tolist()
address = []
for i in range(len(hotel_name)):
    address.append({
        "hotel name" : hotel_name[i],
        "city" : city_name[i],
        "country" : country_name[i]
    })

In [49]:
# Create a map using state centroid coordinates to set markers
marker_locations = ideal_city_df[['lattitude', 'longitude']]


# Create a marker_layer using the poverty list to fill the info box
fig = gmaps.figure()
markers = gmaps.marker_layer(marker_locations,
    info_box_content=[f"Hotel : {hotel}" for hotel in address])
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='420px'))

[]